export const SAVE_BOOK_REQUEST ='SAVE_BOOK_REQUEST';
export const FETCH_BOOK_REQUEST ='FETCH_BOOK_REQUEST';
export const UPDATE_BOOK_REQUEST ='UPDATE_BOOK_REQUEST';
export const BOOK_SUCCESS ='BOOK_SUCCESS';
export const BOOK_FAILURE ='BOOK_FAILURE';
export const DELETE_BOOK_REQUEST='DELETE_BOOK_REQUEST';


export const FETCH_LANGUAGE_REQUEST ='FETCH_BOOK_REQUEST';
export const LANGUAGE_SUCCESS ='LANGUAGE_SUCCESS';
export const LANGUAGE_FAILURE ='LANGUAGE_FAILURE';